stages:
  - build
  - mirror

build:
  image: node
  stage: build
  script:
    - >
      sed -i 's/"version": "kibana"/"version": "4.6"/g' package.json
    - npm install --quiet
    - patch node_modules/@elastic/plugin-helpers/tasks/build/create_build.js < build_package_without_kibana.patch
    - patch node_modules/@elastic/plugin-helpers/tasks/build/create_package.js < create_package_without_kibana.patch
    - npm run build --quiet
  artifacts:
    paths:
      - build/*.zip

mirror:github:
  image: debian
  stage: mirror
  script:
    - apt-get update && apt-get install -y git
    - git clone --mirror https://git.bitsensor.io/front-end/elastalert-kibana-plugin.git mirror-github
    - cd mirror-github
    - git remote add github https://$MIRROR_GITHUB_USER:$MIRROR_GITHUB_PASSWORD@$MIRROR_GITHUB_URL
    - git push -u github -q --mirror
  when: always
